# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1my68TKBr0-g7nNCT7dUW51Ex06e2boIm
"""

s_alg = input().split()
s_geo = input().split()
s_trygono = input().split()
ns_alg = set(s_alg)
ns_geo = set(s_geo)
ns_trygono = set(s_trygono)
vse = ns_alg & ns_geo & ns_trygono
if len(vse) > 0:
  print(' '.join(vse))
else:
  print('Все три задачи никто не решил')